TOOL = /home/jwlee/Spermatogenesis/tools/
BWA = $(TOOL)bwa-0.7.17/
CELLRANGER = $(TOOL)cellranger-3.0.2/cellranger

DATA = /home/jwlee/Spermatogenesis/data/
TRANSCRIPTOME = $(DATA)refdata-cellranger-mm10-3.0.0

SAMPLE_IDS = NS_SW1 NS_SW2 NS_SW3 NS_SW4

all: tmp.sh latest
.PHONY += latest

tmp.sh:
	@echo "make -f /home/jwlee/Spermatogenesis/program/Makefile.whole -C /home/jwlee/Spermatogenesis/result" > $@

%/outs/filtered_feature_bc_matrix.h5:
	$(CELLRANGER) count --transcriptome=$(TRANSCRIPTOME) --fastqs=$(abspath $(DATA)) --id=$(firstword $(subst /, ,$@)) --sample=$(firstword $(subst /, ,$@)) 1> $(firstword $(subst /, ,$@)).cellranger.count.stdout 2> $(firstword $(subst /, ,$@)).cellranger.count.stderr

%/asdf: %/outs/filtered_feature_bc_matrix.h5
	$(CELLRANGER) reanalyze --id=$(firstword $(subst /, , $@))_reanalyze --matrix=$(abspath $<)

latest: $(foreach id,$(SAMPLE_IDS),$(id)/asdf)
